# Generated by Django 5.2.6 on 2025-09-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('quartier', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('on_the_way', 'En route'), ('in_progress', 'En cours'), ('resolved', 'Terminé')], default='pending', max_length=20)),
                ('technician_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
